'use client';

import "./globals.css";
import AppBar from "@/components/AppBar";

import { Provider } from "react-redux";
import { store } from "@/redux/store";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en" >
      <body className="min-h-full flex flex-col">
        <Provider store={store}>
        <div className="container">
          <AppBar />
            <main>
              {children}
            </main>
        </div>
        </Provider>
      </body>
    </html>
  );
}
