'use client';

import "./globals.css";
import AppBar from "@/components/AppBar";

import { Provider } from "react-redux";
import { store } from "@/redux/store";
import ReduxProvider from "@/redux/ReduxProvider";
import { AppThemeProvider } from "@/context/AppThemeContext";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en" >
      <body className="min-h-full flex flex-col">
        {/* <Provider store={store}> */}
        <ReduxProvider>
          <AppThemeProvider>
          <div className="container">
            <AppBar />
            <main>{children}</main>
          </div>
          </AppThemeProvider>
        </ReduxProvider>
        {/* </Provider> */}
      </body>
    </html>
  );
}
